module.exports = `<!DOCTYPE html>
<html><body style="margin:0;padding:0;background:#f5f6f3;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f6f3;padding:24px 0;">
<tr><td align="center">
<table role="presentation" width="640" cellpadding="0" cellspacing="0" style="max-width:640px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;">
  <tr><td style="background:#1b3d26;padding:24px 32px;">
    <span style="font-family:Georgia,serif;font-size:22px;font-weight:bold;color:#ffffff;letter-spacing:1px;">MISTLETOE CONSTRUCTION</span><br>
    <span style="font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#7d9a82;letter-spacing:2px;">THE REALTOR EMAIL SERIES · 14 EMAILS · DOUGLAS COUNTY, OREGON</span>
  </td></tr>
  <tr><td style="padding:24px 32px 4px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6;color:#4a524c;">
    Preview of the full realtor drip — all 14 emails, in send order, on a progressively-spaced cadence (day 0 &rarr; 260). Merge fields like <code>{{first_name}}</code> fill in per recipient at send time.
  </td></tr>
  <tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 01 &nbsp;·&nbsp; SENDS DAY 0</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>A roofer your Douglas County deals can actually count on</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>I'm Alex Smith — I run Mistletoe Construction, a family-owned roofing company out of Riddle (Oregon CCB #255729, Owens Corning contractor). We work every town you sell in, from Roseburg to {{city_or_glide}}.</p>
<p>Here's why I'm in your inbox: roofs kill more Douglas County deals than almost anything else on the inspection report. Moss nobody dealt with, a 24-year-old shingle field, a mystery stain in the attic — and suddenly your closing date is a negotiation.</p>
<p>When that happens, you need a roofer who answers the phone, gets on the roof fast, and gives you a written, photographed answer you can hand to the other side. That's the entire way we operate.</p>
<p>Save this number: <strong>(541) 670-5005</strong> — call or text either way. Over the next few weeks I'll send a handful of short notes on how we help agents specifically — pre-listing inspections, repair credits, roof certifications. No spam, and unsubscribing takes one click.</p>
<p>— Alex</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 02 &nbsp;·&nbsp; SENDS DAY 4</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Price the roof before the buyer's inspector does</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>The cheapest roof problem is the one your seller finds first.</p>
<p>A pre-listing roof inspection takes us about an hour. You get a written report with photos of every issue — moss, lifted shingles, flashing, boots, gutters — before the buyer's inspector climbs up there with their own camera.</p>
<p>What that buys your listing:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'>No surprises at negotiation. You already know what's up there and what it costs to fix.</li><li style='margin:0 0 8px'>Small fixes before showings. A $400 repair now beats a $4,000 credit demand later.</li><li style='margin:0 0 8px'>A document buyers trust. "Roof inspected and serviced last month, report attached" changes how a house reads.</li></ul>
<p>We turn these around fast because listing timelines don't wait. Call or text <strong>(541) 670-5005</strong> when you're prepping your next listing — even if the answer is "roof's fine, here's the proof," that's worth having in the folder.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 03 &nbsp;·&nbsp; SENDS DAY 9</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Repair credit vs. price cut: the roof math that saves deals</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>When a roof issue shows up mid-transaction, there are three ways out — and they are not equal:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'>Price cut. Fast, but buyers mentally double the real repair cost. A $6,000 roof issue becomes a $12,000 ask.</li><li style='margin:0 0 8px'><strong>Repair credit. Better</strong> — but lenders cap credits, and the buyer still closes on a broken roof they now have to manage.</li><li style='margin:0 0 8px'><strong>Fix it before closing. Usually the cheapest path for your seller</strong> — because the repair costs what it costs, not what a nervous buyer fears it costs.</li></ul>
<p>The catch with option three is speed: you need a licensed roofer who can quote from the inspection report within a day or two and get the work done inside the contingency window. That's a lane we've built our scheduling around — written scope, photos of the completed work, documentation for the file.</p>
<p>Next time an inspection report lands with a roofing section that makes everyone frown: <strong>(541) 670-5005</strong>. We'll give you real numbers the same week.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 04 &nbsp;·&nbsp; SENDS DAY 15</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>That green roof is costing your seller money</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>You've seen it on half your listings: the north roof slope is green. In the Umpqua Valley — 130+ rainy days a year — moss is basically a native species.</p>
<p>Two things every agent should know about it:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'>It reads as neglect. Buyers see a mossy roof and assume the whole house was maintained the same way. It suppresses offers well beyond the actual cost of fixing it.</li><li style='margin:0 0 8px'><strong>Never let anyone pressure wash it. Pressure washing strips the protective granules and can void the shingle warranty</strong> — turning a cosmetic issue into a real one. (This one comes up constantly; it's worth remembering.)</li></ul>
<p>Done right — gentle removal, treatment, zinc strips to keep it from coming back — a typical job runs a few hundred dollars and dramatically changes how a listing photographs. We can usually fit pre-listing moss work in fast, because we know photos are waiting.</p>
<p>Green roof on the next walkthrough? <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 05 &nbsp;·&nbsp; SENDS DAY 22</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>"How old is that roof?" — what underwriters want to see</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>"How old is that roof?" — the question that stalls files. The seller thinks 2012, the county shows no permit, and now underwriting or the buyer's insurer wants answers before anyone signs anything.</p>
<p>What actually satisfies that question is documentation from a licensed contractor: roof type and material, estimated remaining life, and condition of the field, flashing, and penetrations — in writing, with photos, from a company whose license number (CCB #255729) anyone can verify with the state in two minutes.</p>
<p>We write these up after a physical inspection, and they've settled everything from insurance-binder questions to "the appraiser flagged the roof" moments. Wet-season closings especially: insurers get nervous about Oregon roofs from October to May, and a current inspection letter calms the whole file down.</p>
<p>If a transaction needs a roof answer in writing, that's a same-week call for us: <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 06 &nbsp;·&nbsp; SENDS DAY 31</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Your pocket roofer for pending sales (tarps included)</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>Here's the practical one — the three ways agents actually use us:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'>The 2 a.m. tarp. A storm hits a pending sale, water's coming in, closing is in twelve days. We tarp fast so the deal survives long enough to fix it properly. Save the number now, not that night: <strong>(541) 670-5005</strong>.</li><li style='margin:0 0 8px'><strong>The honest opinion. Text us photos from a walkthrough and we'll tell you straight whether you're looking at a $500 repair or a replacement conversation</strong> — before your client falls in love or walks away.</li><li style='margin:0 0 8px'><strong>The closing gift that isn't a candle. Our Home Care Membership ($49/mo</strong> — annual roof and gutter inspection, storm checks, priority service, photo reports) is a genuinely useful first-year gift for buyers new to Oregon roofs. Some agents cover the first few months; their clients remember it every time it rains.</li></ul>
<p>That's the whole pitch: a licensed local roofer who treats your transaction timeline like it matters. Coffee's on us if you want to put a face to the name.</p>
<p>— Alex Smith, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 07 &nbsp;·&nbsp; SENDS DAY 42</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>The 5 roof red flags you can spot at any showing</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>You don't need to climb a ladder to read a roof. From the driveway, five things tell you most of the story:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'><strong>Granules in the gutters or the downspout splash</strong> — the shingles are shedding their sun protection, and the clock is running.</li><li style='margin:0 0 8px'><strong>Curling or cupping edges</strong> — heat and age; the field is near the end of its life.</li><li style='margin:0 0 8px'><strong>Dark streaks or green fuzz</strong> — algae and moss; cosmetic now, costly if ignored.</li><li style='margin:0 0 8px'><strong>A sagging or wavy ridgeline</strong> — possible decking or moisture trouble underneath; the one to take seriously.</li><li style='margin:0 0 8px'><strong>Interior ceiling stains</strong> — a leak that's already inside the house.</li></ul>
<p>None of these mean "walk away." They mean "know what you're looking at before you write or price." Spot one on a walkthrough? Snap a photo and text it to me — I'll tell you straight whether it's a $400 fix or a real conversation, no charge and no sales pitch.</p>
<p>Text a roof photo any time: <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 08 &nbsp;·&nbsp; SENDS DAY 56</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Metal vs. asphalt: what to tell buyers in the Umpqua Valley</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>Buyers ask you about roofs, so here's the plain-English version you can repeat with confidence.</p>
<p>Asphalt shingles — most homes here. Lower upfront cost, 20–30 years in our climate, easy to repair and match. The right choice for most sellers and most budgets.</p>
<p>Metal — standing seam or exposed-fastener. Two to three times the cost upfront, but 40–70 years, sheds moss and rain beautifully, and carries a Class A fire rating that matters more every wildfire season. Buyers planning to stay put love it.</p>
<p>The honest answer to "which is better?" is "better for what?" — and being the agent who can actually explain that builds trust fast.</p>
<p>Our full buyer guides are on the site — lifespan, cost, resale — and you're welcome to forward them to any client chewing on the decision. Want the links, or a quick roof read on a specific listing? <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 09 &nbsp;·&nbsp; SENDS DAY 74</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Wildfire season and the roof questions buyers now ask</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>Every summer more Oregon buyers ask the same thing: "Is this house safe if a fire comes through?" The roof is the first honest answer.</p>
<p>Three things worth knowing:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'><strong>Class A is the standard. Most asphalt and all metal roofs we install carry the top fire rating</strong> — embers landing on the roof are the number-one way homes ignite, so this is the real protection.</li><li style='margin:0 0 8px'>The edges matter as much as the field. Ember-resistant vents, clean gutters, and enclosed eaves keep embers from getting underneath.</li><li style='margin:0 0 8px'><strong>It's an insurance conversation now. Insurers are pricing</strong> — and even declining — based on roof age and fire resilience, so a current roof and documentation can keep a policy (and a closing) alive.</li></ul>
<p>If you've got a listing in a higher-risk area, or a buyer who's nervous, I'll do a quick wildfire-resilience read on the roof and put it in writing.</p>
<p><strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 10 &nbsp;·&nbsp; SENDS DAY 96</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>How to read a roof inspection report without panicking</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>A roofing section on an inspection report can look scarier than it is. Here's how to triage one in thirty seconds:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'><strong>Cosmetic / maintenance</strong> — moss, minor granule loss, a little debris, worn sealant. Real, cheap, and almost never a deal-breaker.</li><li style='margin:0 0 8px'><strong>Component repairs</strong> — a few lifted shingles, a flashing detail, a pipe boot. Usually hundreds, not thousands, and quotable fast.</li><li style='margin:0 0 8px'><strong>Systemic</strong> — widespread curling, multiple leaks, decking damage, a roof past its life. This is the replace-or-negotiate conversation, and it deserves a real number, not a guess.</li></ul>
<p>The mistake is treating all three the same and letting a $600 problem read like a $16,000 one. Send me the report — I'll translate the roofing section into plain language and rough numbers, same day, so you walk into the negotiation knowing exactly where the leverage is.</p>
<p>Forward it any time: <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 11 &nbsp;·&nbsp; SENDS DAY 124</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Add $10k of curb-appeal value from the roofline down</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>The fastest curb-appeal win most sellers skip is the top third of the house.</p>
<p>A tired roofline drags down every listing photo — streaked shingles, a sagging gutter, peeling fascia, a downspout hanging loose. Buyers read it as "deferred maintenance everywhere" before they've seen the kitchen.</p>
<p>The fix is usually cheap relative to the return: a soft-wash moss treatment, gutters cleaned and re-secured, fascia touched up, and — if the shingles are near end-of-life — knowing whether a fresh field is worth it before listing rather than after a lowball.</p>
<p>I'll walk a pre-listing roofline with you and hand over a short, prioritized punch list: what's worth doing, what's not, and what it costs. Most sellers spend a little and photograph a lot better.</p>
<p>Prepping a listing? <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 12 &nbsp;·&nbsp; SENDS DAY 160</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Financing a new roof so the deal still closes</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>Sometimes the roof really does need replacing mid-deal — and that doesn't have to end the transaction. A few paths I've seen close:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'>Seller replaces before closing. Cleanest for everyone; the cost is the cost, and the listing gets a brand-new-roof headline.</li><li style='margin:0 0 8px'>Repair or replacement credit. Works within lender limits; the buyer closes and schedules the work.</li><li style='margin:0 0 8px'><strong>Escrow holdback. Funds set aside at closing, roof done right after</strong> — keeps the timeline moving.</li><li style='margin:0 0 8px'>Buyer financing or our membership. Homeowner financing options, plus a maintenance membership that spreads care over time for buyers new to Oregon roofs.</li></ul>
<p>The key is a fast, firm number so both sides negotiate reality instead of fear. I'll put together a one-page options sheet for a specific deal — real scope, real cost, real timeline — that you can hand to either side.</p>
<p>When a roof is the last thing standing between you and the table: <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 13 &nbsp;·&nbsp; SENDS DAY 205</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Winter listings: the roof problems that show up Nov-Feb</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>Winter is when Oregon roofs tell the truth. The leaks that hid all summer show up the first week of steady rain — right when your winter inventory is trying to close.</p>
<p>What to watch from November on:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'><strong>Water intrusion at valleys and flashing</strong> — summer-dry gaps that only leak under sustained rain.</li><li style='margin:0 0 8px'><strong>Overflowing or ice-blocked gutters</strong> — water backing up under the shingle edge and into the fascia.</li><li style='margin:0 0 8px'><strong>Attic condensation</strong> — poor ventilation that reads as a "leak" but is really trapped moisture, and spooks buyers either way.</li></ul>
<p>A quick pre-winter or pre-listing check catches these before they become an inspection surprise or a mid-escrow emergency. And if one does pop during a pending sale, we tarp fast so the closing survives.</p>
<p>Got listings going live this winter? Let's get ahead of it: <strong>(541) 670-5005</strong>.</p>
<p>— Alex, Mistletoe Construction · CCB #255729</p></td></tr>
<tr><td style='padding:26px 32px 6px;'><div style='font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:2px;color:#3f9128;font-weight:bold;'>EMAIL 14 &nbsp;·&nbsp; SENDS DAY 260</div><div style='font-family:Georgia,serif;font-size:19px;font-weight:bold;color:#1b3d26;margin-top:4px;'>Let's make it official: a referral partnership</div><div style='font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#4a524c;margin-top:2px;'>Subject line</div></td></tr><tr><td style='padding:8px 32px 26px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#1f1f1f;border-bottom:1px solid #e6ebe6;'><p>Hi {{first_name}},</p>
<p>We've been in each other's orbit for a few months now — so here's the straight ask: let's make it a real partnership.</p>
<p>What that looks like from my side:</p>
<ul style='margin:0 0 16px;padding-left:22px'><li style='margin:0 0 8px'><strong>Priority service for anyone you send</strong> — your clients go to the front of the line, and they get an honest read, not an upsell.</li><li style='margin:0 0 8px'><strong>Co-branded pre-listing roof reports</strong> — your name and logo on the documentation you hand sellers. It makes you look thorough, because you are.</li><li style='margin:0 0 8px'><strong>A real thank-you for referrals that close</strong> — I take care of the people who take care of me, and I'll tell you exactly how.</li></ul>
<p>You get a roofer who protects your closings and makes you look good doing it. I get to work with agents who value doing it right. That's the whole deal.</p>
<p>Grab fifteen minutes and let's set it up — coffee's on me: <strong>(541) 670-5005</strong>.</p>
<p>— Alex Smith, Mistletoe Construction · CCB #255729</p></td></tr>
  <tr><td style="background:#f5f6f3;padding:20px 32px;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.6;color:#4a524c;">
    Mistletoe Construction LLC · 595 E Third St, Riddle, OR 97469 · (541) 670-5005<br>
    Oregon CCB #255729 · <a href="https://mistletoeconstruction.com" style="color:#3f9128;">mistletoeconstruction.com</a>
  </td></tr>
</table>
</td></tr></table>
</body></html>`;
